// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloHttpService) DeepCopyInto(out *HelloHttpService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloHttpService.
func (in *HelloHttpService) DeepCopy() *HelloHttpService {
	if in == nil {
		return nil
	}
	out := new(HelloHttpService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelloHttpService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloHttpServiceList) DeepCopyInto(out *HelloHttpServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HelloHttpService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloHttpServiceList.
func (in *HelloHttpServiceList) DeepCopy() *HelloHttpServiceList {
	if in == nil {
		return nil
	}
	out := new(HelloHttpServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HelloHttpServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloHttpServiceSpec) DeepCopyInto(out *HelloHttpServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloHttpServiceSpec.
func (in *HelloHttpServiceSpec) DeepCopy() *HelloHttpServiceSpec {
	if in == nil {
		return nil
	}
	out := new(HelloHttpServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelloHttpServiceStatus) DeepCopyInto(out *HelloHttpServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelloHttpServiceStatus.
func (in *HelloHttpServiceStatus) DeepCopy() *HelloHttpServiceStatus {
	if in == nil {
		return nil
	}
	out := new(HelloHttpServiceStatus)
	in.DeepCopyInto(out)
	return out
}
