name: Build Operator
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Install Operator Framework
      run: |
        RELEASE_VERSION=v0.10.0 curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        mkdir -p $(go env GOPATH)/bin && mv operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu $(go env GOPATH)/bin/operator-sdk

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: $(go env GOPATH)/bin/operator-sdk build raelga/hello-operator
